version: "3.3"
services:

  frontend:
    image: 549652764117.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - todo
    - login

  login:
    image: 549652764117.dkr.ecr.us-east-1.amazonaws.com/login:latest
    container_name: login
    depends_on:
    - users
    
  todo:
    image: 549652764117.dkr.ecr.us-east-1.amazonaws.com/todo:latest
    container_name: todo
    depends_on:
    - redis
    
  users:
    image: 549652764117.dkr.ecr.us-east-1.amazonaws.com/users:latest
    container_name: users
    image: users
     
  redis:
    container_name: redis
    image: redis
